server:
  port: 80

spring:
  datasource:
    # url: jdbc:h2:./micropos;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:postgresql://localhost:5432/micropos
    url: jdbc:mysql://localhost:3306/micropos
    driver-class-name: com.mysql.jdbc.Driver
    username: micropos
    password: owokfsen
    # Possible fix to connection timeout.
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: validate
      #ddl-auto: updateExisting
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

logging:
  #file: micropos.log

  level:
    org.springframework: INFO
