server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micropos
    driver-class-name: com.mysql.jdbc.Driver
    username: micropos
    password: --------
    # Possible fix to connection timeout.
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 4
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1
    validation-interval: 30000
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

logging:
  #file: micropos.log

  level:
    org.springframework: INFO

micropos:
  timecard:
    folder: timecard/

  auth:
    header: MicroPOS-Pin

  backup:
    #cron: 0 0/10 * * * *
    cron: 0 0 3 * * *
    enabled: true
    history: 14
    external: E:/
    folder: backup/
    prefix: auto_
    database: micropos
