server:
  port: 80

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./micropos;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: validate
      #ddl-auto: updateExisting
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  file: micropos.log

  level:
    org.springframework: INFO
